#!/usr/bin/expect -f

set timeout 2
set username [exec lpass show --username "corp"]
set password [exec lpass show --password "corp"]

exec /opt/cisco/anyconnect/bin/vpn disconnect cerner

spawn /opt/cisco/anyconnect/bin/vpn -s connect cerner

expect "Username: \[as027811\]"
send "$username\r"

expect "Password: "
send "$password\r"

expect "accept? \[y/n\]: "
send "y\r"

interact
